## Solution to the dominoes problem

In [11]:
import time

def dominoes(n):
    if n <= 1:
        return 1
    else:
        return dominoes(n-2) + dominoes(n-1)
    
def dominoes2(n):
    res = [0]*(n+1)
    res[0] = 1
    res[1] = 1
    for i in range(2,n+1):
        res[i] = res[i-1] + res[i-2]
    return res[n]
    
def dominoes3(n):
    dp0 = 1
    dp1 = 1
    dp2 = 1
    for i in range(2,n+1):
        dp0 = dp1
        dp1 = dp2
        dp2 = dp0 + dp1
    return dp2
        
    
s = time.time()
for i in range(1,45):
    print(dominoes(i), end = " ")
e = time.time()
print("Elapsed time: {}s".format(e-s))
s = time.time()
for i in range(1,45):
    print(dominoes2(i), end = " ")
e = time.time()
print("Elapsed time: {}s".format(e-s))

s = time.time()
for i in range(1,45):
    print(dominoes3(i), end = " ")
e = time.time()
print("Elapsed time: {}s".format(e-s))


Elapsed time: 0.0001277923583984375s
1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 24157817 39088169 63245986 102334155 165580141 267914296 433494437 701408733 1134903170 Elapsed time: 0.008267641067504883s
1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 24157817 39088169 63245986 102334155 165580141 267914296 433494437 701408733 1134903170 Elapsed time: 0.0011742115020751953s


## Hateville

Case when I do NOT pick the i-th donation:

$$HV(i) = HV(i-1)$$

Case when I pick the i-th donation:

$$HV(i) = HV(i-2) + D[i]$$

Summing it all:

$$HV(i) = \begin{cases} 0 & \mbox{if i = 0} \\ D[1] & \mbox{ if i = 1} \\ max(HV(i-1), HV(i-2)+D[i]) & \mbox{if } n \geq 2 \end{cases}$$


$$DP(i) = \begin{cases} 0 & \mbox{if i = 0} \\ D[1] & \mbox{ if i = 1} \\ max(DP(i-1), DP(i-2)+D[i]) & \mbox{if } n \geq 2 \end{cases}$$


In [6]:
def hateville(D, n):
    dp = [0]*(n+1)
    if n > 0:
        dp[1] = D[0]
    for i in range(2, n+1):
        dp[i] = max(dp[i-1],dp[i-2] + D[i-1])
    #print(dp)  
    return dp[n]

D = [10,5,5,8,4,7,12]

print("Donations: {}".format(D))
for i in range(len(D)+1):
    print("Solution for {}: {}".format(D[0:i],hateville(D, i)))
print("\n\n")

D1 = [10,1,1,10,1,1,10]

print("Donations: {}".format(D1))
for i in range(len(D1)+1):
    print("Solution for {}: {}".format(D1[0:i],hateville(D1, i)))
    


Donations: [10, 5, 5, 8, 4, 7, 12]
Solution for []: 0
Solution for [10]: 10
Solution for [10, 5]: 10
Solution for [10, 5, 5]: 15
Solution for [10, 5, 5, 8]: 18
Solution for [10, 5, 5, 8, 4]: 19
Solution for [10, 5, 5, 8, 4, 7]: 25
Solution for [10, 5, 5, 8, 4, 7, 12]: 31



Donations: [10, 1, 1, 10, 1, 1, 10]
Solution for []: 0
Solution for [10]: 10
Solution for [10, 1]: 10
Solution for [10, 1, 1]: 11
Solution for [10, 1, 1, 10]: 20
Solution for [10, 1, 1, 10, 1]: 20
Solution for [10, 1, 1, 10, 1, 1]: 21
Solution for [10, 1, 1, 10, 1, 1, 10]: 30


### A more elegant solution



In [14]:
def hateville(D, n):
    dp = [0, D[0]]
    for i in range(1, n):
        dp.append(max(dp[-1],dp[-2] + D[i]))
     
    return dp[-1]

def hateville_space(D,n):
    dp = [0, D[0]]
    for i in range(1,n):
        new_val = max(dp[1],dp[0]+D[i])
        dp[0] = dp[1]
        dp[1] = new_val
    
    return dp[-1]
    
D = [10,5,5,8,4,7,12]

print("Donations: {}".format(D))
for i in range(len(D)+1):
    print("Solution for {}: {}".format(D[0:i],hateville(D, i)))
    print("Solution for {}: {}".format(D[0:i],hateville_space(D, i)))
print("\n\n")

D1 = [10,1,1,10,1,1,10]

print("Donations: {}".format(D1))
for i in range(len(D1)+1):
    print("Solution for {}: {}".format(D1[0:i],hateville(D1, i)))
    print("Solution for {}: {}".format(D1[0:i],hateville_space(D1, i)))

Donations: [10, 5, 5, 8, 4, 7, 12]
Solution for []: 10
Solution for []: 10
Solution for [10]: 10
Solution for [10]: 10
Solution for [10, 5]: 10
Solution for [10, 5]: 10
Solution for [10, 5, 5]: 15
Solution for [10, 5, 5]: 15
Solution for [10, 5, 5, 8]: 18
Solution for [10, 5, 5, 8]: 18
Solution for [10, 5, 5, 8, 4]: 19
Solution for [10, 5, 5, 8, 4]: 19
Solution for [10, 5, 5, 8, 4, 7]: 25
Solution for [10, 5, 5, 8, 4, 7]: 25
Solution for [10, 5, 5, 8, 4, 7, 12]: 31
Solution for [10, 5, 5, 8, 4, 7, 12]: 31



Donations: [10, 1, 1, 10, 1, 1, 10]
Solution for []: 10
Solution for []: 10
Solution for [10]: 10
Solution for [10]: 10
Solution for [10, 1]: 10
Solution for [10, 1]: 10
Solution for [10, 1, 1]: 11
Solution for [10, 1, 1]: 11
Solution for [10, 1, 1, 10]: 20
Solution for [10, 1, 1, 10]: 20
Solution for [10, 1, 1, 10, 1]: 20
Solution for [10, 1, 1, 10, 1]: 20
Solution for [10, 1, 1, 10, 1, 1]: 21
Solution for [10, 1, 1, 10, 1, 1]: 21
Solution for [10, 1, 1, 10, 1, 1, 10]: 30
Solution

### Hateville and solution

This also gets the indexes of the houses

In [9]:
def hateville(D, n):
    dp = [0]*(n+1)
    if n > 0:
        dp[1] = D[0]
    for i in range(2, n+1):
        dp[i] = max(dp[i-1],dp[i-2] + D[i-1])

    return build_solution(D,dp,n)

def build_solution(D, dp, i):
    if i == 0:
        return []
    elif i == 1:
        return [0]
    else:
        if dp[i] == dp[i-1]:
            sol = build_solution(D, dp, i-1)
        else:
            sol = build_solution(D, dp, i-2)
            sol.append(i-1)
    return sol

D = [10,5,5,8,4,7,12]
print("Donations: {}".format(D))
for i in range(len(D)+1):
    HV = hateville(D, i)
    print("Donors for {}: {}. Donations: {}".format(D[0:i],HV,sum([D[x] for x in HV])))
print("\n\n")

D1 = [10,1,1,10,1,1,10]
print("Donations: {}".format(D1))
for i in range(len(D1)+1):
    HV = hateville(D1, i)
    print("Donors for {}: {}. Donations: {}".format(D1[0:i],HV,sum([D1[x] for x in HV])))
    


Donations: [10, 5, 5, 8, 4, 7, 12]
Donors for []: []. Donations: 0
Donors for [10]: [0]. Donations: 10
Donors for [10, 5]: [0]. Donations: 10
Donors for [10, 5, 5]: [0, 2]. Donations: 15
Donors for [10, 5, 5, 8]: [0, 3]. Donations: 18
Donors for [10, 5, 5, 8, 4]: [0, 2, 4]. Donations: 19
Donors for [10, 5, 5, 8, 4, 7]: [0, 3, 5]. Donations: 25
Donors for [10, 5, 5, 8, 4, 7, 12]: [0, 2, 4, 6]. Donations: 31



Donations: [10, 1, 1, 10, 1, 1, 10]
Donors for []: []. Donations: 0
Donors for [10]: [0]. Donations: 10
Donors for [10, 1]: [0]. Donations: 10
Donors for [10, 1, 1]: [0, 2]. Donations: 11
Donors for [10, 1, 1, 10]: [0, 3]. Donations: 20
Donors for [10, 1, 1, 10, 1]: [0, 3]. Donations: 20
Donors for [10, 1, 1, 10, 1, 1]: [0, 3, 5]. Donations: 21
Donors for [10, 1, 1, 10, 1, 1, 10]: [0, 3, 6]. Donations: 30


## Knapsack


In [8]:
import numpy as np
import math


def knapsack(w, p, C):
    n = len(w)
    DP = np.zeros((n + 1, C + 1))
    for i in range(1, n+1):
        for c in range(1, C+1):
            not_taken = DP[i-1][c]
            if w[i-1]  > c:
                taken = -math.inf
            else:
                taken = DP[i-1][c - w[i-1]] + p[i-1]
                
            DP[i][c] = max( not_taken, taken)
    #print(DP)
    return DP[n][C]


w = [4,2,3,4]
p = [10,7,8,6]
C = 9
print(knapsack(w,p,C))

w = [4, 7, 11, 3, 3, 3, 11, 10, 6]
p = [1,2,3,4, 12, 5,8,7, 11]
C = 78

print(knapsack(w,p,C))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 10. 10. 10. 10. 10. 10.]
 [ 0.  0.  7.  7. 10. 10. 17. 17. 17. 17.]
 [ 0.  0.  7.  8. 10. 15. 17. 18. 18. 25.]
 [ 0.  0.  7.  8. 10. 15. 17. 18. 18. 25.]]
25.0
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.  2.  2.  2.  2.  3.  3.  3.  3.  3.  3.  3.
   3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  